"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
import { requireProfile } from "@/lib/auth/session";
import { can } from "@/lib/auth/rbac";

export type ActionState = { error?: string; success?: string };

const leaseSchema = z
  .object({
    unitId: z.string().uuid("Select a unit"),
    tenantId: z.string().uuid("Select a tenant"),
    startDate: z.string().min(1, "Start date is required"),
    endDate: z.string().min(1, "End date is required"),
    annualRent: z.coerce.number().min(0, "Rent cannot be negative"),
    securityDeposit: z.coerce.number().min(0).default(0),
    paymentMethod: z.enum(["cheque", "bank_transfer", "direct_debit", "cash", "card", "online"]),
    installmentCount: z.coerce.number().int(),
    ejariContractNumber: z.string().max(60).optional(),
    ejariRegisteredOn: z.string().optional(),
    ejariExpiry: z.string().optional(),
    agencyFee: z.coerce.number().min(0).optional(),
    ejariFee: z.coerce.number().min(0).optional(),
    notes: z.string().max(2000).optional(),
  })
  .refine((v) => new Date(v.endDate) > new Date(v.startDate), {
    message: "The end date must fall after the start date",
    path: ["endDate"],
  })
  .refine((v) => [1, 2, 3, 4, 6, 12].includes(v.installmentCount), {
    message: "Rent must be split into 1, 2, 3, 4, 6 or 12 payments",
    path: ["installmentCount"],
  });

/**
 * Creates a tenancy and its payment schedule in one step.
 *
 * The cheque schedule is generated by the database function rather than here,
 * so the dates and the rounding remainder are computed the same way no matter
 * what creates the lease.
 */
export async function createLease(
  _prev: ActionState,
  formData: FormData
): Promise<ActionState> {
  const profile = await requireProfile();
  if (!can(profile.role, "leases.manage")) {
    return { error: "You do not have permission to create tenancies." };
  }

  const parsed = leaseSchema.safeParse(Object.fromEntries(formData));
  if (!parsed.success) {
    return { error: parsed.error.issues[0]?.message ?? "Check the form and try again." };
  }
  const input = parsed.data;

  const supabase = await createClient();

  const { data: lease, error } = await supabase
    .from("leases")
    .insert({
      unit_id: input.unitId,
      tenant_id: input.tenantId,
      lease_number: "", // filled by the autonumber trigger
      status: "draft",
      start_date: input.startDate,
      end_date: input.endDate,
      annual_rent_aed: input.annualRent,
      security_deposit_aed: input.securityDeposit,
      payment_method: input.paymentMethod,
      installment_count: input.installmentCount,
      ejari_contract_number: input.ejariContractNumber || null,
      ejari_registered_on: input.ejariRegisteredOn || null,
      ejari_expiry: input.ejariExpiry || null,
      ejari_status: input.ejariContractNumber ? "registered" : "not_registered",
      agency_fee_aed: input.agencyFee ?? null,
      ejari_fee_aed: input.ejariFee ?? null,
      notes: input.notes || null,
      created_by: profile.id,
    })
    .select("id, unit_id")
    .single();

  if (error) {
    // The exclusion constraint fires when the dates clash with a live tenancy.
    if (error.message.includes("leases_no_overlap")) {
      return {
        error:
          "Those dates overlap an existing tenancy on this unit. Terminate or adjust the other contract first.",
      };
    }
    return { error: error.message };
  }

  const { error: scheduleError } = await supabase.rpc("generate_lease_installments", {
    p_lease_id: lease.id,
  });

  if (scheduleError) {
    return {
      error: `Tenancy created, but the payment schedule failed: ${scheduleError.message}`,
    };
  }

  revalidatePath("/leases");
  revalidatePath(`/units/${lease.unit_id}`);
  redirect(`/leases/${lease.id}`);
}

const statusSchema = z.object({
  leaseId: z.string().uuid(),
  status: z.enum([
    "draft", "pending_signature", "active", "expiring", "renewed",
    "terminated", "cancelled", "expired",
  ]),
  reason: z.string().max(500).optional(),
});

export async function updateLeaseStatus(
  _prev: ActionState,
  formData: FormData
): Promise<ActionState> {
  const profile = await requireProfile();
  if (!can(profile.role, "leases.manage")) {
    return { error: "You do not have permission to change tenancy status." };
  }

  const parsed = statusSchema.safeParse(Object.fromEntries(formData));
  if (!parsed.success) return { error: "Invalid request." };
  const { leaseId, status, reason } = parsed.data;

  const supabase = await createClient();
  const terminal = status === "terminated" || status === "cancelled";

  const { error } = await supabase
    .from("leases")
    .update({
      status,
      terminated_on: terminal ? new Date().toISOString().slice(0, 10) : null,
      termination_reason: terminal ? (reason ?? null) : null,
    })
    .eq("id", leaseId);

  if (error) return { error: error.message };

  revalidatePath(`/leases/${leaseId}`);
  return { success: "Tenancy status updated." };
}

const installmentSchema = z.object({
  installmentId: z.string().uuid(),
  leaseId: z.string().uuid(),
  status: z.enum(["scheduled", "presented", "cleared", "bounced", "cancelled"]),
  bounceReason: z.string().max(300).optional(),
});

/**
 * Records the outcome of a rent cheque.
 *
 * Marking one cleared is what posts collected income to the ledger (via the
 * database trigger), which is in turn what the owner statement is built from.
 */
export async function updateInstallment(
  _prev: ActionState,
  formData: FormData
): Promise<ActionState> {
  const profile = await requireProfile();
  if (!can(profile.role, "leases.manage") && !can(profile.role, "finance.manage")) {
    return { error: "You do not have permission to record payments." };
  }

  const parsed = installmentSchema.safeParse(Object.fromEntries(formData));
  if (!parsed.success) return { error: "Invalid request." };
  const { installmentId, leaseId, status, bounceReason } = parsed.data;

  const today = new Date().toISOString().slice(0, 10);
  const supabase = await createClient();

  const { data: current } = await supabase
    .from("lease_installments")
    .select("amount_aed")
    .eq("id", installmentId)
    .single();

  const { error } = await supabase
    .from("lease_installments")
    .update({
      status,
      cleared_on: status === "cleared" ? today : null,
      presented_on: status === "presented" || status === "cleared" ? today : null,
      bounced_on: status === "bounced" ? today : null,
      bounce_reason: status === "bounced" ? (bounceReason ?? null) : null,
      amount_paid_aed: status === "cleared" ? (current?.amount_aed ?? 0) : 0,
    })
    .eq("id", installmentId);

  if (error) return { error: error.message };

  revalidatePath(`/leases/${leaseId}`);
  revalidatePath("/finance");
  return {
    success:
      status === "cleared"
        ? "Payment recorded and posted to the ledger."
        : "Payment status updated.",
  };
}

const occupantSchema = z.object({
  leaseId: z.string().uuid(),
  fullName: z.string().min(2, "Enter the occupant's full name").max(160),
  relationship: z.string().max(60).optional(),
  nationality: z.string().max(60).optional(),
  emiratesId: z.string().max(30).optional(),
  passportNumber: z.string().max(30).optional(),
});

/**
 * Adds a declared occupant.
 *
 * A database trigger clears the lease's Ejari sync stamp on any change here,
 * which is what starts the 30-day clock the compliance calendar reports on.
 */
export async function addOccupant(
  _prev: ActionState,
  formData: FormData
): Promise<ActionState> {
  // Tenants may declare their own occupants, so this only needs a signed-in
  // user; the RLS policy decides whether they may write to this lease.
  await requireProfile();

  const parsed = occupantSchema.safeParse(Object.fromEntries(formData));
  if (!parsed.success) {
    return { error: parsed.error.issues[0]?.message ?? "Check the form." };
  }
  const input = parsed.data;

  const supabase = await createClient();
  const { error } = await supabase.from("lease_occupants").insert({
    lease_id: input.leaseId,
    full_name: input.fullName,
    relationship: input.relationship || null,
    nationality: input.nationality || null,
    emirates_id: input.emiratesId || null,
    passport_number: input.passportNumber || null,
  });

  if (error) return { error: error.message };

  revalidatePath(`/leases/${input.leaseId}`);
  revalidatePath("/compliance");
  return {
    success: `${input.fullName} declared. Update Ejari within 30 days to stay compliant.`,
  };
}

export async function removeOccupant(
  _prev: ActionState,
  formData: FormData
): Promise<ActionState> {
  await requireProfile();
  const leaseId = String(formData.get("leaseId") ?? "");
  const occupantId = String(formData.get("occupantId") ?? "");

  const supabase = await createClient();
  const { error } = await supabase
    .from("lease_occupants")
    .update({ removed_on: new Date().toISOString().slice(0, 10) })
    .eq("id", occupantId);

  if (error) return { error: error.message };

  revalidatePath(`/leases/${leaseId}`);
  revalidatePath("/compliance");
  return { success: "Occupant removed. Update Ejari within 30 days." };
}

/**
 * Confirms that the declared-occupant list has been pushed to Ejari, which
 * clears the compliance flag until the list changes again.
 */
export async function markOccupantsSynced(
  _prev: ActionState,
  formData: FormData
): Promise<ActionState> {
  const profile = await requireProfile();
  if (!can(profile.role, "ejari.manage")) {
    return { error: "You do not have permission to update Ejari records." };
  }

  const leaseId = String(formData.get("leaseId") ?? "");
  const now = new Date().toISOString();
  const supabase = await createClient();

  // Stamp the individual occupant rows first: the lease-level trigger clears
  // the lease stamp whenever an occupant row changes, so it must be set last.
  const { error: occupantError } = await supabase
    .from("lease_occupants")
    .update({ ejari_synced_at: now })
    .eq("lease_id", leaseId)
    .is("removed_on", null);

  if (occupantError) return { error: occupantError.message };

  const { error } = await supabase
    .from("leases")
    .update({ ejari_occupants_synced_at: now })
    .eq("id", leaseId);

  if (error) return { error: error.message };

  revalidatePath(`/leases/${leaseId}`);
  revalidatePath("/compliance");
  return { success: "Ejari occupant record marked as current." };
}

const tenantSchema = z.object({
  isCompany: z.boolean().default(false),
  fullName: z.string().min(2, "Tenant name is required").max(160),
  companyTradeLicence: z.string().max(60).optional(),
  email: z.string().email("Enter a valid email").or(z.literal("")).optional(),
  phone: z.string().max(30).optional(),
  whatsapp: z.string().max(30).optional(),
  nationality: z.string().max(60).optional(),
  emiratesId: z.string().max(30).optional(),
  emiratesIdExpiry: z.string().optional(),
  passportNumber: z.string().max(30).optional(),
  employer: z.string().max(120).optional(),
});

export type TenantActionState = ActionState & {
  tenant?: { id: string; full_name: string; is_company: boolean };
};

/**
 * Creates a tenant record. Kept separate from lease creation so the same
 * tenant can be reused across renewals and additional units.
 */
export async function createTenant(
  _prev: TenantActionState,
  formData: FormData
): Promise<TenantActionState> {
  const profile = await requireProfile();
  if (!can(profile.role, "leases.manage")) {
    return { error: "You do not have permission to add tenants." };
  }

  const parsed = tenantSchema.safeParse({
    ...Object.fromEntries(formData),
    isCompany: formData.get("isCompany") === "on",
  });
  if (!parsed.success) {
    return { error: parsed.error.issues[0]?.message ?? "Check the form and try again." };
  }
  const input = parsed.data;

  const supabase = await createClient();
  const { data: tenant, error } = await supabase
    .from("tenants")
    .insert({
      is_company: input.isCompany,
      full_name: input.fullName,
      company_trade_licence: input.companyTradeLicence || null,
      email: input.email || null,
      phone: input.phone || null,
      whatsapp: input.whatsapp || input.phone || null,
      nationality: input.nationality || null,
      emirates_id: input.emiratesId || null,
      emirates_id_expiry: input.emiratesIdExpiry || null,
      passport_number: input.passportNumber || null,
      employer: input.employer || null,
    })
    .select("id, full_name, is_company")
    .single();

  if (error) return { error: error.message };

  revalidatePath("/leases/new");
  return { success: `${input.fullName} added.`, tenant };
}
